# Generated by Django 4.2.4 on 2023-09-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_reviewrating_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
    ]
